### ISSUE TITLE
Extend fDOMElement appendElement() and appendElementNS() with optional parameter $asTextNode

### ISSUE THREAD

**Issue by FloEberle** [theseer/fDOMDocument#32]
Hi Arne

Is there a reason that fDOMElement->appendElement() and  fDOMElement->appendElementNS() do not support the (optional) parameter $asTextNode ? Sometimes this would be really helpful. I guess it would be easy to implement (just forward it to ownerDocument->createElement)  and I could also send a pull request if you like.

//Update: Pull Request already done https://github.com/theseer/fDOMDocument/pull/33

Cheers!
Flo

**Comment by theseer** [comment]
Can you add the Method appendElementPrefix to the list of methods that support it?
I'll create a new release then.

**Comment by FloEberle** [comment]
of course, see https://github.com/theseer/fDOMDocument/pull/34

**Comment by theseer** [comment]
Thanks. Release forthcoming.

**Comment by FloEberle** [comment]
thanks aswell :)
