### ISSUE TITLE
Failing test with PHPUnit 7.2

### ISSUE THREAD

**Issue by DavidPrevot** [theseer/fDOMDocument#35]
Hi,

In Debian, since the recent upload of PHPUnit 7.2, we noticed that the following fDOMDocument internal test now fails:

```
1) TheSeer\fDOM\Tests\XPathQueryTest::testFindingKeysInQueryWorks
TheSeer\fDOM\fDOMException: parsing string failed

/usr/share/php/TheSeer/fDOMDocument/fDOMDocument.php:171
/tmp/autopkgtest-lxc._7z7siya/downtmp/build.TCp/src/tests/XPathQuery.test.php:53
```
https://ci.debian.net/data/packages/unstable/amd64/p/php-fdomdocument/latest-autopkgtest/log.gz

Please note that the following internal phpDox test also fails, which might be related:

```
1) TheSeer\phpDox\GlobalConfigTest::testTryingToLoadInvalidConfigThrowsException
Failed asserting that exception of type "TheSeer\fDOM\fDOMException" matches expected exception "\TheSeer\phpDox\ConfigException". Message was: "loading file '/tmp/autopkgtest-lxc.dv7ktfvx/downtmp/build.6e0/src/tests/data/config/broken.xml' failed." at
/usr/share/php/TheSeer/fDOMDocument/fDOMDocument.php:147
/tmp/autopkgtest-lxc.dv7ktfvx/downtmp/build.6e0/src/tests/Unit/config/GlobalConfigTest.php:82
/tmp/autopkgtest-lxc.dv7ktfvx/downtmp/build.6e0/src/tests/Unit/config/GlobalConfigTest.php:92
```
https://ci.debian.net/data/packages/unstable/amd64/p/phpdox/latest-autopkgtest/log.gz

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902008

**Comment by theseer** [comment]
Interesting.
No code has been changed for quite a while and tests run fine up to PHPUnit 7.1.5.
Starting with PHPUnit 7.2.0, this one test fails.

Investigating.

**Comment by theseer** [comment]
This is a bug in PHPUnit. One I'm afraid even I caused.
I'll open a bug and provide a PR.

**Comment by theseer** [comment]
While I consider the broken test a side effect of an unclean behavior within PHPUnit, fDOM itself also should clear the libxml error buffer before looking for errors. Global state for the win ;)

Thanks for finding this.

When https://github.com/sebastianbergmann/phpunit/pull/3190 the problem should be fixed.
I'll leave this  open so I can fix the behavior in fDOMDocument as well.

**Comment by DavidPrevot** [comment]
> When sebastianbergmann/phpunit#3190 got merged, the problem should be fixed.

Confirmed. I just rebuilt phpunit with your fix and ran the tests on both fDOMDocument and phpDox. Thanks a lot for your quick response!

Regards

David

**Comment by FelixSchwarz** [comment]
> I'll leave this open so I can fix the behavior in fDOMDocument as well.

PHPUnit was fixed quite a while ago but this repo still "needs" a fix :-)

**Comment by theseer** [comment]
As this project is to be Archived, I'll close this issue. Sorry for not addressing this.
