### ISSUE TITLE
Several type hints missing

### ISSUE THREAD

**Issue by nickel715** [theseer/fDOMDocument#37]
Serveral methods and attributes returning fDOM... objects but only hinting regular DOM... objects. 

For example the property `fDOMDocument->firstChild` returns a `fDOMNode` but is only hinted as `DOMNode` 

In `fDOMNode` I found this `@property  fDOMDocument $ownerDocument`, I would propose to add this to all classes of fDOM, what do you think?

**Comment by theseer** [comment]
Sounds like a good idea.

It might also be required for various methods that fDOM does not overwrite and thus doesn't "adjust" the returned type for.

**Comment by theseer** [comment]
As this project is to be Archived, I'll close this issue. Sorry for not addressing this.
